version: '3.7'
services:
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    hostname: gitlab-runner
    restart: unless-stopped
    volumes:
      - '.gitlab-runner-config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - runner-network

networks:
  runner-network:
    name: runner-network
