concurrent = 1
log_level = "error"
log_format = "text"
check_interval = 15

[session_server]
  session_timeout = 1800

[[runners]]
  name = "refonte-runner"
  url = "https://gitlab.com/"
  token = "myawesometoken"
  executor = "docker"
  # [runners.custom_build_dir]
  # [runners.cache]
  #   [runners.cache.s3]
  #   [runners.cache.gcs]
  #   [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    # oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
    network_mode = "runner-network"
    shm_size = 0
